# The URL the site will be built for
base_url = "https://norionanalytics.com"
theme = "hayflow"
# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
#highlight_code = false

[extra]
# Put all your custom variables here
name = { first = "Norion Analytics", last = "" }
description = "Data Ontologies for Space Domain Awareness"
sections = ["info", "ai"]

links = [
   { icon = "fa-solid fa-envelope", url = "mailto:trevor@norionanalytics.com" },
]
